org: joseant
app: api-starwars
service: api-starwars

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  profile: serverless
  environment:
    TABLE_NAME: ${self:service}-${opt:stage, 'dev'}-characters
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-${opt:stage, 'dev'}-characters"

plugins:
  - serverless-offline
  - serverless-openapi-documentation

custom:
  documentation:
    api:
      info:
        title: API Star Wars
        description: API para gestionar personajes de Star Wars
        version: '1.0.0'
    
functions:
  createCharacter:
    handler: src/handlers/createCharacter.createCharacter
    events:
      - http:
          path: character
          method: post
          cors: true
          documentation:
            summary: Crear un personaje
            description: Crea un nuevo personaje en la base de datos
            requestBody:
              description: Datos del personaje
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: ID del personaje
                        example: 1
            responses:
              '201':
                description: Personaje creado correctamente
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        message:
                          type: string
                          example: "Personaje creado con éxito"
              '500':
                description: Error al crear personaje
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        error:
                          type: string
                          example: "Error interno del servidor"

  getCharacters:
    handler: src/handlers/getCharacters.getCharacters
    events:
      - http:
          path: characters
          method: get
          cors: true
          documentation:
            summary: "Obtener todos los personajes"
            description: "Recupera todos los personajes de la tabla de DynamoDB."
            responses:
              '200':
                description: "Se recuperó exitosamente la lista de personajes."
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        data:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                                description: ID del personaje
                                example: 1
                              nombre:
                                type: string
                                description: Nombre del personaje
                                example: "Luke Skywalker"     
              '500':
                description: "Error en el servidor"
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        error:
                          type: string
                          example: "Error interno del servidor"

resources:
  Resources:
    CharactersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
